'use strict';
let state, selected, tab='active', view='jobs';
const $=id=>document.getElementById(id);
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
const add=(parent,...children)=>{children.forEach(c=>parent.append(c));return parent;};
const option=(value,text)=>{const n=el('option','',text);n.value=value;return n;};
function options(select,labels,first){select.replaceChildren();if(first)select.append(option('',first));Object.entries(labels).forEach(([k,v])=>select.append(option(k,v)));}
function notice(text,error=false){$('notice').textContent=text;$('notice').className=error?'error':'';}
function date(value){const d=new Date(value);return Number.isNaN(d.valueOf())?value:new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(d);}
const linked=key=>state.contacts.filter(c=>c.job_key===key);
const companyPending=j=>state.contacts.some(c=>!c.job_key&&c.company===j.raw.company);
const decision=j=>j.assessment.decision;
function badge(text,kind=''){return el('span','badge '+kind,text);}
async function request(path,data){const r=await fetch(path,data?{method:'POST',headers:{'Content-Type':'application/json','X-JobPilot-Token':state.csrf_token},body:JSON.stringify(data)}:{});const result=await r.json();if(!r.ok)throw Error(result.error||'操作失败');return result;}
async function save(button,path,data,message){button.disabled=true;try{await request(path,data);await load();notice(message);}catch(e){notice(e.message,true);}finally{button.disabled=false;}}
async function load(){state=await request('/api/state');$('rules').textContent='资格规则 '+state.rules_version;renderStats();if(view==='jobs')renderJobs();if(view==='contacts')renderContacts();if(view==='activity')await renderActivity();}
function renderStats(){const active=state.jobs.filter(j=>decision(j)!=='source_removed');const entries=[['在库岗位',active.length,'另有 '+(state.jobs.length-active.length)+' 条已移除记录'],['可人工评估',active.filter(j=>decision(j)==='review_candidate').length,'通过初筛，仍需核对任职要求'],['资格待核实',active.filter(j=>decision(j)==='needs_verification').length,'保留疑点，不用高分覆盖资格'],['已沟通公司',new Set(state.contacts.map(c=>c.company)).size,state.contacts.length+' 条沟通记录 · 与正式投递分开']];$('stats').replaceChildren(...entries.map(([label,count,help])=>add(el('div','stat'),el('div','stat-label',label),el('strong','',count),el('small','',help))));$('contact-count').textContent=state.contacts.length;}
function renderJobs(){const tabs={active:'全部在库',candidate:'可人工评估',contacted:'已沟通岗位',removed:'已移除'};$('tabs').replaceChildren(...Object.entries(tabs).map(([k,label])=>{const b=el('button',k===tab?'active':'',label);b.onclick=()=>{tab=k;renderJobs();};return b;}));
const q=$('search').value.trim().toLowerCase(),filter=$('decision').value,review=$('review-filter').value;
let jobs=state.jobs.filter(j=>(tab==='removed'?decision(j)==='source_removed':decision(j)!=='source_removed')&&(tab!=='candidate'||decision(j)==='review_candidate')&&(tab!=='contacted'||linked(j.key).length)&&(!filter||decision(j)===filter)&&(!review||j.review===review)&&(!q||[j.raw.company,j.raw.title,j.raw.jd].join(' ').toLowerCase().includes(q)));
const priority={review_candidate:0,needs_verification:1,unscored:2,low_match:3,insufficient_jd:4,excluded:5,source_removed:6};jobs.sort((a,b)=>($('sort').value==='recommended'?priority[decision(a)]-priority[decision(b)]:0)||(b.raw.score||0)-(a.raw.score||0));
$('result-count').textContent=jobs.length+' 个岗位';if(!jobs.some(j=>j.key===selected))selected=jobs[0]?.key;
$('job-list').replaceChildren(...jobs.map(j=>{const r=j.raw,b=el('button','job-card'+(j.key===selected?' selected':''));b.setAttribute('aria-pressed',String(j.key===selected));const top=el('div','card-top'),copy=el('div');add(copy,el('div','company',r.company||'公司未标注'),el('div','job-title',r.title));const score=el('div','score',r.score_reason?String(r.score):'—');score.append(el('small','',r.score_reason?'原始评分':'未评分'));add(top,el('div','avatar',(r.company||'职').slice(0,1)),copy,score);const badges=el('div','badges');badges.append(badge(state.labels[decision(j)],decision(j)));if(linked(j.key).length)badges.append(badge('已沟通','contact'));else if(companyPending(j))badges.append(badge('公司已沟通 · 岗位待关联','contact'));if(j.review!=='unreviewed')badges.append(badge(state.reviews[j.review]));if(j.application_state!=='not_applied')badges.append(badge(state.applications[j.application_state]));add(b,top,el('div','meta',[r.city,r.salary||'薪资待确认',r.experience].filter(Boolean).join(' · ')),badges);b.onclick=()=>{selected=j.key;renderJobs();};return b;}));if(!jobs.length)$('job-list').append(el('div','empty','暂无符合条件的岗位\n试试调整筛选条件或同步来源。'));renderDetail(jobs.find(j=>j.key===selected));}
function renderDetail(j){const root=$('detail');root.replaceChildren();if(!j){root.append(el('div','empty','选择一个岗位，查看匹配依据与下一步。'));return;}const r=j.raw,a=j.assessment;add(root,el('div','eyebrow',(j.source==='boss'?'BOSS 直聘':j.source)+' / 岗位详情'),el('h2','',r.title),el('p','',r.company+' · '+(r.city||'地点待确认')));const badges=el('div','badges');add(badges,badge(state.labels[a.decision],a.decision),badge(state.applications[j.application_state]));root.append(badges);
try{const u=new URL(r.url);if(['http:','https:'].includes(u.protocol)){const link=el('a','source','查看原始岗位 ↗');link.href=u.href;link.target='_blank';link.rel='noreferrer noopener';root.append(link);}}catch{}
const assessment=el('div','assessment');assessment.append(el('strong','',a.eligibility==='fail'?'资格不符合 · 已硬性排除':'资格与完整度检查'));const reasons=[...a.eligibility_reasons,...a.quality_reasons];if(reasons.length){const ul=el('ul');reasons.forEach(x=>ul.append(el('li','',x.evidence)));assessment.append(ul);}else assessment.append(el('p','','当前规则未发现阻断项，仍需核对全部任职要求。'));root.append(assessment);add(root,el('h3','','匹配依据 · 原始评分 '+(r.score_reason?r.score:'未评分')),el('div','score-reason',r.score_reason||'该岗位尚未评分，或因资格 / JD 质量检查跳过。'));const jd=el('details');add(jd,el('summary','','展开完整职位描述'),el('div','jd',r.jd||'暂无 JD'));root.append(jd);
const reviewSection=el('section');reviewSection.append(el('h3','','我的审阅'));const select=el('select');select.setAttribute('aria-label','我的审阅结论');options(select,state.reviews);select.value=j.review;const text=el('textarea');text.placeholder='写下核实结果、考虑原因或下一步…';text.setAttribute('aria-label','审阅备注');text.value=j.review_note;const btn=el('button','primary','保存审阅');btn.onclick=()=>save(btn,'/api/review',{key:j.key,fingerprint:j.fingerprint,state:select.value,note:text.value},'审阅已保存');add(reviewSection,select,text,btn);root.append(reviewSection);
const application=el('details');application.append(el('summary','','更新正式申请状态 · '+state.applications[j.application_state]));const aps=el('select');aps.setAttribute('aria-label','正式申请状态');options(aps,state.applications);aps.value=j.application_state;const evidence=el('textarea');evidence.placeholder='填写本人确认或提交成功依据。打招呼请记在沟通记录中。';evidence.setAttribute('aria-label','申请状态依据');const ab=el('button','','保存申请状态');ab.onclick=()=>save(ab,'/api/application',{key:j.key,fingerprint:j.fingerprint,state:aps.value,note:evidence.value},'申请状态已记录，没有执行提交');add(application,aps,evidence,ab);root.append(application);
add(root,el('h3','','沟通记录'));const contacts=linked(j.key);contacts.forEach(c=>root.append(el('p','hint',date(c.occurred_at)+' · '+state.contact_types[c.kind]+' · '+c.note)));if(!contacts.length)root.append(el('p','hint',companyPending(j)?'这家公司已有沟通记录，具体岗位待关联。请到“沟通记录”核对。':'暂无关联记录；公司级记录可在“沟通记录”中关联。'));const cb=el('button','','＋ 记录已发生的沟通');cb.onclick=()=>openContact(j);add(root,cb,el('p','hint','保存仅更新本地台账，不会发送消息或投递。'));}
function renderContacts(){const root=$('contacts-list');root.replaceChildren();if(!state.contacts.length)root.append(el('div','empty','还没有沟通记录。可以先记录已发生的打招呼或回复。'));for(const c of state.contacts){const row=el('article','contact-row'),body=el('div','contact-body');add(body,el('h3','',c.company+(c.person?' · '+c.person:'')),badge(state.contact_types[c.kind],'contact'),el('p','',c.note));const select=el('select');select.setAttribute('aria-label',c.company+'关联岗位');select.append(option('','具体岗位待关联'));state.jobs.filter(j=>j.raw.company===c.company).forEach(j=>select.append(option(j.key,j.raw.title+(decision(j)==='source_removed'?'（已移除）':'')+' · '+j.source_id.slice(0,8))));select.value=c.job_key||'';select.onchange=()=>save(select,'/api/contacts/link',{id:c.id,job_key:select.value},'岗位关联已更新');body.append(select);add(row,el('div','avatar',c.company.slice(0,1)),body,el('time','',date(c.occurred_at)));root.append(row);}}
async function renderActivity(){const rows=await request('/api/events');const names={imported:'导入岗位',import_updated:'更新岗位',human_review:'人工审阅',manual_application_update:'申请状态记录',contact_link:'沟通关联'};const root=$('activity-list');root.replaceChildren(...rows.map(r=>{const j=state.jobs.find(j=>j.key===r.job_key),copy=el('div');let note=r.details;if(['imported','import_updated'].includes(r.kind))note='已保存来源快照和规则评估';else try{const d=JSON.parse(note);note=(state.reviews[d.state]||state.applications[d.state]||d.decision||'')+' '+(d.note||d.evidence||'');if(r.kind==='contact_link')note=d.to?'已关联具体岗位':'已取消岗位关联';}catch{}add(copy,el('strong','',names[r.kind]||r.kind),el('p','',j?j.raw.company+' / '+j.raw.title:r.job_key),el('p','',note));return add(el('div','activity-row'),el('time','',date(r.at)),copy);}));}
function contactJobs(preselect){const form=$('contact-form'),company=form.elements.company.value,select=form.elements.job_key;select.replaceChildren(option('','具体岗位待关联'));state.jobs.filter(j=>j.raw.company===company).forEach(j=>select.append(option(j.key,j.raw.title+' · '+j.source_id.slice(0,8))));select.value=preselect||'';}
function openContact(job){const form=$('contact-form');form.reset();form.elements.company.value=job?.raw.company||'';options(form.elements.kind,state.contact_types);form.elements.occurred_at.value=new Date(Date.now()+8*3600000).toISOString().slice(0,16);contactJobs(job?.key);$('contact-dialog').showModal();}
$('contact-form').elements.company.addEventListener('input',()=>contactJobs());
$('contact-form').onsubmit=async event=>{event.preventDefault();const form=event.target,button=form.querySelector('[type=submit]'),data=Object.fromEntries(new FormData(form));data.occurred_at+=':00+08:00';button.disabled=true;try{await request('/api/contacts',data);$('contact-dialog').close();await load();notice('沟通记录已保存');}catch(e){notice(e.message,true);}finally{button.disabled=false;}};
$('close-dialog').onclick=()=>$('contact-dialog').close();$('new-contact').onclick=()=>openContact();
document.querySelectorAll('.nav').forEach(button=>button.onclick=async()=>{view=button.dataset.view;document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b===button));['jobs','contacts','activity'].forEach(v=>$(v+'-view').hidden=v!==view);$('page-title').textContent={jobs:'把机会，变成下一步。',contacts:'让每一次沟通都有回响。',activity:'看得见的求职进展。'}[view];try{if(view==='jobs')renderJobs();if(view==='contacts')renderContacts();if(view==='activity')await renderActivity();}catch(e){notice(e.message,true);}});
['search','decision','review-filter','sort'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',()=>renderJobs()));
$('sync').onclick=async()=>{const b=$('sync');b.disabled=true;notice('正在读取 BossHunter 已保存的岗位并重新核对规则…');try{const r=await request('/api/sync',{});await load();notice(`同步完成：新增 ${r.inserted} 条，更新 ${r.updated} 条，未变更 ${r.unchanged} 条。`);}catch(e){notice(e.message,true);}finally{b.disabled=false;}};
(async()=>{try{state=await request('/api/state');options($('decision'),state.labels,'所有资格状态');options($('review-filter'),state.reviews,'所有审阅状态');await load();}catch(e){notice('工作台暂不可用：'+e.message,true);}})();
